In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.Series()

Series([], dtype: object)

In [ ]:
ice_cream_flavors = [
    "Chocolate",
    "Vanilla",
    "Strawberry",
    "ButterScotch",
] # list
pd.Series(ice_cream_flavors) # Series Object

In [ ]:
pd.Series(ice_cream_flavors)
pd.Series(data = ice_cream_flavors)

In [71]:
ice_cream_flavors = [
    "Chocolate",
    "Vanilla",
    "Strawberry",
    "ButterScotch",
]

days_of_week = ("Mon", "Tue", "Wed", "Thu") # tuple

pd.Series(ice_cream_flavors, days_of_week)
pd.Series(data = ice_cream_flavors, index = days_of_week) # keyword arguments

Mon       Chocolate
Tue         Vanilla
Wed      Strawberry
Thu    ButterScotch
dtype: object

In [70]:
ice_cream_flavors = [
    "Chocolate",
    "Vanilla",
    "Strawberry",
    "ButterScotch",
]

days_of_week = ("Mon", "Tue", "Wed", "Tue")

# the two statements below are equivalent
pd.Series(ice_cream_flavors, days_of_week)
pd.Series(data = ice_cream_flavors, index = days_of_week)

Mon       Chocolate
Tue         Vanilla
Wed      Strawberry
Tue    ButterScotch
dtype: object

In [69]:
pd.Series(index = days_of_week, data = ice_cream_flavors)

Mon       Chocolate
Tue         Vanilla
Wed      Strawberry
Tue    ButterScotch
dtype: object

In [68]:
bunch_of_bools = [True, False, True, True, False] # list
pd.Series(bunch_of_bools)

0     True
1    False
2     True
3     True
4    False
dtype: bool

In [67]:
stock_prices = [120, 121, 119, 116, 115]
time_of_day = ["open", "noon", "afternoon", "close", "after_hours"]
pd.Series(data = stock_prices, index = time_of_day)

open           120
noon           121
afternoon      119
close          116
after_hours    115
dtype: int64

In [66]:
lucky_numbers = [7, 13, 11, 17, 19]
pd.Series(lucky_numbers, dtype = "float") # specify data type

0     7.0
1    13.0
2    11.0
3    17.0
4    19.0
dtype: float64

In [65]:
temperatures = [98.6, 99.1, np.nan, 101.2] # list with NaN value
pd.Series(data = temperatures)

0     98.6
1     99.1
2      NaN
3    101.2
dtype: float64

In [64]:
calorie_info = {
    "Chocolate": 210,
    "Vanilla": 200,
    "Strawberry": 190,
    "ButterScotch": 250,
}

diet =pd.Series(calorie_info) # create Series from a
diet

Chocolate       210
Vanilla         200
Strawberry      190
ButterScotch    250
dtype: int64

In [63]:
diet.index
diet.values

array([210, 200, 190, 250])

In [23]:
pd.Series(data = ("Red", "Blue", "Green"))

0      Red
1     Blue
2    Green
dtype: object

In [26]:
my_set = {"rick", "morty", "summer"}
#pd.Series(my_set)

In [27]:
pd.Series(list(my_set))

0      rick
1     morty
2    summer
dtype: object

In [ ]:
random_data = np.random.randint(1, 100, 5) # array of 5 random integers between 1 and 100
random_data

array([ 2, 42, 64, 66, 76], dtype=int32)

In [19]:
pd.Series(random_data)

0     2
1    42
2    64
3    66
4    76
dtype: int32

In [20]:
diet.values

array([210, 200, 190, 250])

In [22]:
type(diet.values)
type(diet.index)

pandas.core.indexes.base.Index

In [28]:
pd.Series(data = [3,3]).is_unique

False

In [29]:
pd.Series(data = [1,3,6,8]).is_monotonic_increasing

True

In [30]:
pd.Series(data = [1,3,6,9,4,2,6]).is_monotonic_increasing

False

In [31]:
values = range(0,500,20)
nums = pd.Series(data = values)
nums

0       0
1      20
2      40
3      60
4      80
5     100
6     120
7     140
8     160
9     180
10    200
11    220
12    240
13    260
14    280
15    300
16    320
17    340
18    360
19    380
20    400
21    420
22    440
23    460
24    480
dtype: int64

In [32]:
nums.head(5)

0     0
1    20
2    40
3    60
4    80
dtype: int64

In [33]:
nums.tail(8)

17    340
18    360
19    380
20    400
21    420
22    440
23    460
24    480
dtype: int64

In [35]:
nums.head(n=3)

0     0
1    20
2    40
dtype: int64

In [39]:
numbers = pd.Series([1,2,3,np.nan,4,5])
numbers

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64

In [42]:
print(numbers.count())

5


In [43]:
numbers.sum()

np.float64(15.0)

In [44]:
numbers.sum(skipna=False)

np.float64(nan)

In [45]:
numbers.sum(min_count=3)

np.float64(15.0)

In [62]:
numbers.sum(max_count=5)  
# This will raise an error because 'max_count' is not a valid parameter

TypeError: sum() got an unexpected keyword argument 'max_count'

In [47]:
numbers.product()

np.float64(120.0)

In [48]:
numbers.product(skipna=False)

np.float64(nan)

In [46]:
numbers.cumsum()

0     1.0
1     3.0
2     6.0
3     NaN
4    10.0
5    15.0
dtype: float64

In [49]:
numbers.pct_change()

C:\Users\SYS\AppData\Local\Temp\ipykernel_10180\527026991.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change()


0         NaN
1    1.000000
2    0.500000
3    0.000000
4    0.333333
5    0.250000
dtype: float64

In [ ]:
#[1,2,np.nan,np.nan,np.nan,4,5]
#[1,2,2,2,2,4,5] forward fill
#[1,2,4,4,4,4,5] backward fill

In [60]:
#the three lines below are equivalent
numbers.pct_change()
numbers.pct_change(fill_method='pad') #forward fill
numbers.pct_change(fill_method='ffill') # equivalent to 'pad'

C:\Users\SYS\AppData\Local\Temp\ipykernel_10180\3741477364.py:2: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change()
C:\Users\SYS\AppData\Local\Temp\ipykernel_10180\3741477364.py:3: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change(fill_method='pad') #forward fill
C:\Users\SYS\AppData\Local\Temp\ipykernel_10180\3741477364.py:4: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to

0         NaN
1    1.000000
2    0.500000
3    0.000000
4    0.333333
5    0.250000
dtype: float64

In [59]:
numbers.pct_change(fill_method='bfill') #backward fill
numbers.pct_change(fill_method='backfill') # equivalent to 'bfill'

C:\Users\SYS\AppData\Local\Temp\ipykernel_10180\1603756439.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change(fill_method='bfill') #backward fill
C:\Users\SYS\AppData\Local\Temp\ipykernel_10180\1603756439.py:2: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  numbers.pct_change(fill_method='backfill') # equivalent to 'bfill'


0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.000000
5    0.250000
dtype: float64

In [50]:
numbers.mean()

np.float64(3.0)

In [51]:
numbers.median()

np.float64(3.0)

In [52]:
numbers.std()

np.float64(1.5811388300841898)

In [53]:
animals = pd.Series(["cat", "dog", "lion", "tiger", "elephant"])
animals

0         cat
1         dog
2        lion
3       tiger
4    elephant
dtype: object

In [54]:
animals.max()

'tiger'

In [55]:
animals.min()

'cat'

In [56]:
numbers.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

In [57]:
animals.describe()

count       5
unique      5
top       cat
freq        1
dtype: object

In [72]:
numbers.sample(3)

2    3.0
3    NaN
5    5.0
dtype: float64

In [ ]:
s1=pd.Series(values=[5,np.nan,10], index=['a','b','c'])

In [ ]:
s1 =pd.Series([1,2,3], index=["A","B","C"])
s2 =pd.Series([4,5,6], index=['a','b','c'])

In [ ]:
s1 + s2

a    5
b    7
c    9
dtype: int64

In [5]:
s1 = pd.Series(data = [3, 6, np.nan, 12])
s2 = pd.Series(data = [2, 6, np.nan, 12])

In [6]:
s1 == s2 # element-wise comparison
s1.eq(s2) # equivalent to s1 == s2

0    False
1     True
2    False
3     True
dtype: bool

In [7]:
# The two lines below are equivalent
s1 != s2
s1.ne(s2) # equivalent to s1 != s2

0     True
1    False
2     True
3    False
dtype: bool

In [8]:
s1 = pd.Series(
    data = [5, 10, 15],index = ["A", "B", "C"]
)
s2 = pd.Series(
    data = [4, 8, 12, 14],index = ["B", "C", "D", "E"]
)

In [9]:
s1 + s2

A     NaN
B    14.0
C    23.0
D     NaN
E     NaN
dtype: float64

In [10]:
cities = pd.Series(
    data = ["san francisco", "los angeles", "new york", np.nan ]
)

In [11]:
len(cities)

4

In [12]:
type(cities)

pandas.core.series.Series

In [13]:
dir(cities)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '_

In [14]:
list(cities)

['san francisco', 'los angeles', 'new york', nan]

In [15]:
cities

0    san francisco
1      los angeles
2         new york
3              NaN
dtype: object

In [16]:
dict(cities)

{0: 'san francisco', 1: 'los angeles', 2: 'new york', 3: nan}

In [17]:
"new york" in cities

False

In [18]:
3 in cities

True

In [19]:
cities.values

array(['san francisco', 'los angeles', 'new york', nan], dtype=object)

In [20]:
"new york" in cities.values

True